"""PDF report generation with ReportLab."""
import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from config import FEATURE_META, FEATURES

RISK_COLORS = {"Low": "#198754", "Moderate": "#d99a00", "High": "#dc3545"}


def build_pdf(row, clean, result):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
                            topMargin=16 * mm, bottomMargin=16 * mm, title="Heart Risk Report")
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=ss["Title"], textColor=colors.HexColor("#b3122d"), fontSize=22)
    h2 = ParagraphStyle("h2", parent=ss["Heading2"], textColor=colors.HexColor("#222222"), spaceBefore=10)
    small = ParagraphStyle("small", parent=ss["Normal"], fontSize=8, textColor=colors.grey)
    body = ss["BodyText"]

    els = [Paragraph("CardioCheck - Heart Risk Report", h1)]
    els.append(Paragraph(f"Patient: <b>{row['patient']}</b> &nbsp;|&nbsp; Date: {row['created']} "
                         f"&nbsp;|&nbsp; Model: {row['model']} &nbsp;|&nbsp; Report #{row['id']}", body))
    els.append(Spacer(1, 8))

    rc = RISK_COLORS.get(result["risk"], "#333")
    els.append(Paragraph(f"<font size=26 color='{rc}'><b>{result['percent']}%</b></font> "
                         f"<font size=14 color='{rc}'>&nbsp;{result['risk']} risk</font>", body))
    els.append(Paragraph(result["label"], body))

    els.append(Paragraph("Patient inputs", h2))
    data = [["Parameter", "Value"]] + [[FEATURE_META[f]["label"],
                                        _fmt(f, clean[f])] for f in FEATURES]
    t = Table(data, colWidths=[95 * mm, 70 * mm])
    t.setStyle(_table_style())
    els.append(t)

    els.append(Paragraph("Top factors influencing this result", h2))
    data = [["Factor", "Value", "Effect on risk"]]
    for e in result["explanation"][:6]:
        pts = e["impact"] * 100
        data.append([e["label"], e["value"], f"{pts:+.1f} pts"])
    t = Table(data, colWidths=[80 * mm, 50 * mm, 35 * mm])
    t.setStyle(_table_style())
    els.append(t)

    els.append(Paragraph("Recommendations", h2))
    for title, text in result["advice"]:
        els.append(Paragraph(f"<b>{title}:</b> {text}", body))
        els.append(Spacer(1, 3))

    els.append(Spacer(1, 10))
    els.append(Paragraph("Disclaimer: this report is generated by a machine-learning model for educational "
                         "purposes only. It is not a medical diagnosis. Consult a qualified healthcare "
                         "professional for medical advice.", small))
    doc.build(els)
    return buf.getvalue()


def _fmt(f, v):
    m = FEATURE_META[f]
    if m["type"] == "select":
        return m["options"][int(v)]
    return f"{v:g} {m.get('unit', '')}".strip()


def _table_style():
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#b3122d")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f6f6f8")]),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#dddddd")),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ])
